.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Core/Application.h" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Core/Application.h \- Header for the Application module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Brigerad/Core/Core\&.h'\fP
.br
\fC#include 'Brigerad/Events/Event\&.h'\fP
.br
\fC#include 'Brigerad/Core/LayerStack\&.h'\fP
.br
\fC#include 'Brigerad/Events/ApplicationEvent\&.h'\fP
.br
\fC#include 'Brigerad/Core/Window\&.h'\fP
.br
\fC#include 'Brigerad/ImGui/ImGuiLayer\&.h'\fP
.br
\fC#include 'Brigerad/Core/Timestep\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Shader\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Buffer\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/VertexArray\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Renderer\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/OrthographicCamera\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrigerad::Application\fP"
.br
.RI "Base class for the client application using the \fBBrigerad\fP engine\&.
.br
\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Application * \fBBrigerad::CreateApplication\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for the Application module\&. 


.PP
\fBAuthor\fP
.RS 4
Samuel Martel (martelsamuel00@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-01-02
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
