.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Events/ApplicationEvent.h" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Events/ApplicationEvent.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Brigerad/Events/Event\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrigerad::WindowResizeEvent\fP"
.br
.ti -1c
.RI "class \fBBrigerad::WindowCloseEvent\fP"
.br
.ti -1c
.RI "class \fBBrigerad::AppTickEvent\fP"
.br
.ti -1c
.RI "class \fBBrigerad::AppUpdateEvent\fP"
.br
.ti -1c
.RI "class \fBBrigerad::AppRenderEvent\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
