.TH "Brigerad::ImGuiTextComponent" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::ImGuiTextComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImGuiTextComponents\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTextComponent\fP ()=default"
.br
.ti -1c
.RI "\fBImGuiTextComponent\fP (const \fBImGuiTextComponent\fP &)=default"
.br
.ti -1c
.RI "\fBImGuiTextComponent\fP (const std::string &t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtext\fP = 'Placeholder'"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::ImGuiTextComponent::ImGuiTextComponent ()\fC [default]\fP"

.SS "Brigerad::ImGuiTextComponent::ImGuiTextComponent (const \fBImGuiTextComponent\fP &)\fC [default]\fP"

.SS "Brigerad::ImGuiTextComponent::ImGuiTextComponent (const std::string & t)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Brigerad::ImGuiTextComponent::text = 'Placeholder'"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
