.TH "Brigerad::GLShaderUniformField" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::GLShaderUniformField
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenGLShaderUniform\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOpenGLShaderUniformDeclaration::Type\fP \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "uint32_t \fBcount\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "int32_t \fBlocation\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBOpenGLShaderUniformDeclaration::Type\fP Brigerad::GLShaderUniformField::type"

.SS "std::string Brigerad::GLShaderUniformField::name"

.SS "uint32_t Brigerad::GLShaderUniformField::count"

.SS "uint32_t Brigerad::GLShaderUniformField::size\fC [mutable]\fP"

.SS "int32_t Brigerad::GLShaderUniformField::location\fC [mutable]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
