.TH "Brigerad::OpenGLIndexBuffer" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::OpenGLIndexBuffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenGLBuffer\&.h>\fP
.PP
Inherits \fBBrigerad::IndexBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenGLIndexBuffer\fP (uint32_t *indices, uint32_t count)"
.br
.ti -1c
.RI "\fBOpenGLIndexBuffer\fP (void *indices, uint32_t count)"
.br
.ti -1c
.RI "virtual \fB~OpenGLIndexBuffer\fP () override"
.br
.ti -1c
.RI "virtual void \fBBind\fP () const override"
.br
.ti -1c
.RI "virtual void \fBUnbind\fP () const override"
.br
.ti -1c
.RI "virtual uint32_t \fBGetCount\fP () const override"
.br
.ti -1c
.RI "virtual const uint32_t \fBGetId\fP () const override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBm_rendererID\fP"
.br
.ti -1c
.RI "uint32_t \fBm_count\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::OpenGLIndexBuffer::OpenGLIndexBuffer (uint32_t * indices, uint32_t count)"

.SS "Brigerad::OpenGLIndexBuffer::OpenGLIndexBuffer (void * indices, uint32_t count)"

.SS "Brigerad::OpenGLIndexBuffer::~OpenGLIndexBuffer ()\fC [override]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Brigerad::OpenGLIndexBuffer::Bind () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::IndexBuffer\fP\&.
.SS "void Brigerad::OpenGLIndexBuffer::Unbind () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::IndexBuffer\fP\&.
.SS "virtual uint32_t Brigerad::OpenGLIndexBuffer::GetCount () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::IndexBuffer\fP\&.
.SS "virtual const uint32_t Brigerad::OpenGLIndexBuffer::GetId () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::IndexBuffer\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t Brigerad::OpenGLIndexBuffer::m_rendererID\fC [private]\fP"

.SS "uint32_t Brigerad::OpenGLIndexBuffer::m_count\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
