.TH "Brigerad::AnimatedVertex" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::AnimatedVertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddBoneData\fP (uint32_t boneId, float weight)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBposition\fP"
.br
.ti -1c
.RI "glm::vec3 \fBnormal\fP"
.br
.ti -1c
.RI "glm::vec3 \fBtangent\fP"
.br
.ti -1c
.RI "glm::vec3 \fBbinormal\fP"
.br
.ti -1c
.RI "glm::vec2 \fBtexCoord\fP"
.br
.ti -1c
.RI "uint32_t \fBids\fP [4] = {0, 0, 0, 0}"
.br
.ti -1c
.RI "float \fBweights\fP [4] = {0\&.0f, 0\&.0f, 0\&.0f, 0\&.0f}"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Brigerad::AnimatedVertex::AddBoneData (uint32_t boneId, float weight)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 Brigerad::AnimatedVertex::position"

.SS "glm::vec3 Brigerad::AnimatedVertex::normal"

.SS "glm::vec3 Brigerad::AnimatedVertex::tangent"

.SS "glm::vec3 Brigerad::AnimatedVertex::binormal"

.SS "glm::vec2 Brigerad::AnimatedVertex::texCoord"

.SS "uint32_t Brigerad::AnimatedVertex::ids[4] = {0, 0, 0, 0}"

.SS "float Brigerad::AnimatedVertex::weights[4] = {0\&.0f, 0\&.0f, 0\&.0f, 0\&.0f}"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
