.TH "Brigerad::CameraComponent" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::CameraComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Components\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraComponent\fP ()=default"
.br
.ti -1c
.RI "\fBCameraComponent\fP (const \fBCameraComponent\fP &)=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSceneCamera\fP \fBcamera\fP"
.br
.ti -1c
.RI "bool \fBprimary\fP = true"
.br
.ti -1c
.RI "bool \fBfixedAspectRatio\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::CameraComponent::CameraComponent ()\fC [default]\fP"

.SS "Brigerad::CameraComponent::CameraComponent (const \fBCameraComponent\fP &)\fC [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBSceneCamera\fP Brigerad::CameraComponent::camera"

.SS "bool Brigerad::CameraComponent::primary = true"

.SS "bool Brigerad::CameraComponent::fixedAspectRatio = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
