.TH "Brigerad::KeyEvent" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::KeyEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <KeyEvents\&.h>\fP
.PP
Inherits \fBBrigerad::Event\fP\&.
.PP
Inherited by \fBBrigerad::KeyPressedEvent\fP, \fBBrigerad::KeyReleasedEvent\fP, and \fBBrigerad::KeyTypedEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyCode\fP \fBGetKeyCode\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyEvent\fP (\fBKeyCode\fP keycode)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBKeyCode\fP \fBm_keyCode\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::KeyEvent::KeyEvent (\fBKeyCode\fP keycode)\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBKeyCode\fP Brigerad::KeyEvent::GetKeyCode () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBKeyCode\fP Brigerad::KeyEvent::m_keyCode\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
