.TH "Brigerad::OpenGLTexture2D" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::OpenGLTexture2D
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenGLTexture\&.h>\fP
.PP
Inherits \fBBrigerad::Texture2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenGLTexture2D\fP (uint32_t width, uint32_t height, uint8_t channels)"
.br
.ti -1c
.RI "\fBOpenGLTexture2D\fP (const std::string &path)"
.br
.ti -1c
.RI "virtual \fB~OpenGLTexture2D\fP () override"
.br
.ti -1c
.RI "virtual uint32_t \fBGetWidth\fP () const override"
.br
.ti -1c
.RI "virtual uint32_t \fBGetHeight\fP () const override"
.br
.ti -1c
.RI "virtual uint32_t \fBGetRenderID\fP () const override"
.br
.ti -1c
.RI "virtual uint32_t \fBGetFormat\fP () const override"
.br
.ti -1c
.RI "virtual const std::string & \fBGetFilePath\fP () const override"
.br
.ti -1c
.RI "virtual void \fBSetData\fP (void *data, uint32_t size) override"
.br
.ti -1c
.RI "virtual void \fBBind\fP (uint32_t slot=0) const override"
.br
.ti -1c
.RI "virtual bool \fBoperator==\fP (const \fBTexture\fP &other) const override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_path\fP = ''"
.br
.ti -1c
.RI "uint32_t \fBm_width\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBm_height\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBm_rendererID\fP = 0"
.br
.ti -1c
.RI "\fBGLenum\fP \fBm_internalFormat\fP"
.br
.ti -1c
.RI "\fBGLenum\fP \fBm_dataFormat\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::OpenGLTexture2D::OpenGLTexture2D (uint32_t width, uint32_t height, uint8_t channels)"

.SS "Brigerad::OpenGLTexture2D::OpenGLTexture2D (const std::string & path)"

.SS "Brigerad::OpenGLTexture2D::~OpenGLTexture2D ()\fC [override]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual uint32_t Brigerad::OpenGLTexture2D::GetWidth () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Texture\fP\&.
.SS "virtual uint32_t Brigerad::OpenGLTexture2D::GetHeight () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Texture\fP\&.
.SS "virtual uint32_t Brigerad::OpenGLTexture2D::GetRenderID () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Texture\fP\&.
.SS "virtual uint32_t Brigerad::OpenGLTexture2D::GetFormat () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Texture\fP\&.
.SS "virtual const std::string& Brigerad::OpenGLTexture2D::GetFilePath () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Texture\fP\&.
.SS "void Brigerad::OpenGLTexture2D::SetData (void * data, uint32_t size)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Texture\fP\&.
.SS "void Brigerad::OpenGLTexture2D::Bind (uint32_t slot = \fC0\fP) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Texture\fP\&.
.SS "virtual bool Brigerad::OpenGLTexture2D::operator== (const \fBTexture\fP & other) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Texture\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string Brigerad::OpenGLTexture2D::m_path = ''\fC [private]\fP"

.SS "uint32_t Brigerad::OpenGLTexture2D::m_width = 0\fC [private]\fP"

.SS "uint32_t Brigerad::OpenGLTexture2D::m_height = 0\fC [private]\fP"

.SS "uint32_t Brigerad::OpenGLTexture2D::m_rendererID = 0\fC [private]\fP"

.SS "\fBGLenum\fP Brigerad::OpenGLTexture2D::m_internalFormat\fC [private]\fP"

.SS "\fBGLenum\fP Brigerad::OpenGLTexture2D::m_dataFormat\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
