.TH "Brigerad::OpenGLVertexArray" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::OpenGLVertexArray
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenGLVertexArray\&.h>\fP
.PP
Inherits \fBBrigerad::VertexArray\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenGLVertexArray\fP ()"
.br
.ti -1c
.RI "virtual \fB~OpenGLVertexArray\fP ()"
.br
.ti -1c
.RI "virtual void \fBBind\fP () const override"
.br
.ti -1c
.RI "virtual void \fBUnbind\fP () const override"
.br
.ti -1c
.RI "virtual void \fBAddVertexBuffer\fP (const \fBRef\fP< \fBVertexBuffer\fP > &vertexBuffer) override"
.br
.ti -1c
.RI "virtual void \fBSetIndexBuffer\fP (const \fBRef\fP< \fBIndexBuffer\fP > &indexBuffer) override"
.br
.ti -1c
.RI "virtual const std::vector< \fBRef\fP< \fBVertexBuffer\fP > > & \fBGetVertexBuffers\fP () const override"
.br
.ti -1c
.RI "virtual const \fBRef\fP< \fBIndexBuffer\fP > & \fBGetIndexBuffers\fP () const override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBRef\fP< \fBVertexBuffer\fP > > \fBm_vertexBuffers\fP"
.br
.ti -1c
.RI "\fBRef\fP< \fBIndexBuffer\fP > \fBm_indexBuffer\fP"
.br
.ti -1c
.RI "uint32_t \fBm_rendererId\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::OpenGLVertexArray::OpenGLVertexArray ()"

.SS "Brigerad::OpenGLVertexArray::~OpenGLVertexArray ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Brigerad::OpenGLVertexArray::Bind () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::VertexArray\fP\&.
.SS "void Brigerad::OpenGLVertexArray::Unbind () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::VertexArray\fP\&.
.SS "void Brigerad::OpenGLVertexArray::AddVertexBuffer (const \fBRef\fP< \fBVertexBuffer\fP > & vertexBuffer)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::VertexArray\fP\&.
.SS "void Brigerad::OpenGLVertexArray::SetIndexBuffer (const \fBRef\fP< \fBIndexBuffer\fP > & indexBuffer)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::VertexArray\fP\&.
.SS "const std::vector< \fBRef\fP< \fBVertexBuffer\fP > > & Brigerad::OpenGLVertexArray::GetVertexBuffers () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::VertexArray\fP\&.
.SS "const \fBRef\fP< \fBIndexBuffer\fP > & Brigerad::OpenGLVertexArray::GetIndexBuffers () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::VertexArray\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBRef\fP<\fBVertexBuffer\fP> > Brigerad::OpenGLVertexArray::m_vertexBuffers\fC [private]\fP"

.SS "\fBRef\fP<\fBIndexBuffer\fP> Brigerad::OpenGLVertexArray::m_indexBuffer\fC [private]\fP"

.SS "uint32_t Brigerad::OpenGLVertexArray::m_rendererId\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
