.TH "Brigerad::TagComponent" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::TagComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Components\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBto_string\fP ()"
.br
.ti -1c
.RI "\fBTagComponent\fP ()=default"
.br
.ti -1c
.RI "\fBTagComponent\fP (const \fBTagComponent\fP &)=default"
.br
.ti -1c
.RI "\fBTagComponent\fP (const std::string &t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtag\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::TagComponent::TagComponent ()\fC [default]\fP"

.SS "Brigerad::TagComponent::TagComponent (const \fBTagComponent\fP &)\fC [default]\fP"

.SS "Brigerad::TagComponent::TagComponent (const std::string & t)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string Brigerad::TagComponent::to_string ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Brigerad::TagComponent::tag"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
