.TH "Brigerad::ScriptEngineRegistry" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::ScriptEngineRegistry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptEngineRegistry\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterAllTypes\fP ()"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterEntity\fP ()"
.br
.ti -1c
.RI "static void \fBRegisterComponents\fP ()"
.br
.ti -1c
.RI "static void \fBRegisterVec2\fP ()"
.br
.ti -1c
.RI "static void \fBRegisterVec3\fP ()"
.br
.ti -1c
.RI "static void \fBRegisterVec4\fP ()"
.br
.ti -1c
.RI "static void \fBRegisterMat4\fP ()"
.br
.ti -1c
.RI "static void \fBRegisterTexture2D\fP ()"
.br
.ti -1c
.RI "static void \fBRegisterSubTexture2D\fP ()"
.br
.ti -1c
.RI "static void \fBRegisterDrawQuad\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Brigerad::ScriptEngineRegistry::RegisterAllTypes ()\fC [static]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterEntity ()\fC [static]\fP, \fC [private]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterComponents ()\fC [static]\fP, \fC [private]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterVec2 ()\fC [static]\fP, \fC [private]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterVec3 ()\fC [static]\fP, \fC [private]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterVec4 ()\fC [static]\fP, \fC [private]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterMat4 ()\fC [static]\fP, \fC [private]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterTexture2D ()\fC [static]\fP, \fC [private]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterSubTexture2D ()\fC [static]\fP, \fC [private]\fP"

.SS "void Brigerad::ScriptEngineRegistry::RegisterDrawQuad ()\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
