.TH "Brigerad::LightComponent" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::LightComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Components\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLight\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLightComponent\fP ()=default"
.br
.ti -1c
.RI "\fBLightComponent\fP (const glm::vec3 &direction, const glm::vec3 &radiance)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLight\fP \fBlight\fP"
.br
.ti -1c
.RI "bool \fBisPrimary\fP = true"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::LightComponent::LightComponent ()\fC [default]\fP"

.SS "Brigerad::LightComponent::LightComponent (const glm::vec3 & direction, const glm::vec3 & radiance)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBLight\fP Brigerad::LightComponent::light"

.SS "bool Brigerad::LightComponent::isPrimary = true"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
