.TH "Brigerad::Shader" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Shader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Shader\&.h>\fP
.PP
Inherited by \fBBrigerad::OpenGLShader\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBShaderReloadedCallback\fP = std::function< void()>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Shader\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBReload\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBBind\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBUploadUniformBuffer\fP (const \fBUniformBufferBase\fP &uniformBuffer)=0"
.br
.ti -1c
.RI "virtual void \fBSetInt\fP (const std::string &name, int value)=0"
.br
.ti -1c
.RI "virtual void \fBSetIntArray\fP (const std::string &name, int *values, uint32_t count)=0"
.br
.ti -1c
.RI "virtual void \fBSetFloat\fP (const std::string &name, float value)=0"
.br
.ti -1c
.RI "virtual void \fBSetFloat2\fP (const std::string &name, const glm::vec2 &value)=0"
.br
.ti -1c
.RI "virtual void \fBSetFloat3\fP (const std::string &name, const glm::vec3 &value)=0"
.br
.ti -1c
.RI "virtual void \fBSetFloat4\fP (const std::string &name, const glm::vec4 &value)=0"
.br
.ti -1c
.RI "virtual void \fBSetMat3\fP (const std::string &name, const glm::mat3 &value)=0"
.br
.ti -1c
.RI "virtual void \fBSetMat4\fP (const std::string &name, const glm::mat4 &value)=0"
.br
.ti -1c
.RI "virtual const std::string & \fBGetName\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBSetVSMaterialUniformBuffer\fP (\fBBuffer\fP buffer)=0"
.br
.ti -1c
.RI "virtual void \fBSetPSMaterialUniformBuffer\fP (\fBBuffer\fP buffer)=0"
.br
.ti -1c
.RI "virtual const \fBShaderUniformBufferList\fP & \fBGetVSRendererUniforms\fP () const =0"
.br
.ti -1c
.RI "virtual const \fBShaderUniformBufferList\fP & \fBGetPSRendererUniforms\fP () const =0"
.br
.ti -1c
.RI "virtual const \fBShaderUniformBufferDeclaration\fP & \fBGetVSMaterialUniformBuffer\fP () const =0"
.br
.ti -1c
.RI "virtual const \fBShaderUniformBufferDeclaration\fP & \fBGetPSMaterialUniformBuffer\fP () const =0"
.br
.ti -1c
.RI "virtual const \fBShaderResourceList\fP & \fBGetResources\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBAddShaderReloadedCallback\fP (const \fBShaderReloadedCallback\fP &callback)=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRef\fP< \fBShader\fP > \fBCreate\fP (const std::string &filePath)"
.br
.ti -1c
.RI "static \fBRef\fP< \fBShader\fP > \fBCreateFromString\fP (const std::string &source)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::vector< \fBRef\fP< \fBShader\fP > > \fBs_AllShaders\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBBrigerad::Shader::ShaderReloadedCallback\fP =  std::function<void()>"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Brigerad::Shader::~Shader ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Brigerad::Shader::Reload ()\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::Bind () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::UploadUniformBuffer (const \fBUniformBufferBase\fP & uniformBuffer)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetInt (const std::string & name, int value)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetIntArray (const std::string & name, int * values, uint32_t count)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetFloat (const std::string & name, float value)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetFloat2 (const std::string & name, const glm::vec2 & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetFloat3 (const std::string & name, const glm::vec3 & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetFloat4 (const std::string & name, const glm::vec4 & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetMat3 (const std::string & name, const glm::mat3 & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetMat4 (const std::string & name, const glm::mat4 & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual const std::string& Brigerad::Shader::GetName () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "\fBRef\fP< \fBShader\fP > Brigerad::Shader::Create (const std::string & filePath)\fC [static]\fP"

.SS "\fBRef\fP< \fBShader\fP > Brigerad::Shader::CreateFromString (const std::string & source)\fC [static]\fP"

.SS "virtual void Brigerad::Shader::SetVSMaterialUniformBuffer (\fBBuffer\fP buffer)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::SetPSMaterialUniformBuffer (\fBBuffer\fP buffer)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual const \fBShaderUniformBufferList\fP& Brigerad::Shader::GetVSRendererUniforms () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual const \fBShaderUniformBufferList\fP& Brigerad::Shader::GetPSRendererUniforms () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual const \fBShaderUniformBufferDeclaration\fP& Brigerad::Shader::GetVSMaterialUniformBuffer () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual const \fBShaderUniformBufferDeclaration\fP& Brigerad::Shader::GetPSMaterialUniformBuffer () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual const \fBShaderResourceList\fP& Brigerad::Shader::GetResources () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SS "virtual void Brigerad::Shader::AddShaderReloadedCallback (const \fBShaderReloadedCallback\fP & callback)\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::OpenGLShader\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBRef\fP<\fBShader\fP> > Brigerad::Shader::s_AllShaders\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
