.TH "Brigerad::OpenGLFontAtlas" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::OpenGLFontAtlas
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenGLFontAtlas\&.h>\fP
.PP
Inherits \fBBrigerad::FontAtlas\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenGLFontAtlas\fP (const std::string &fontPath)"
.br
.ti -1c
.RI "virtual \fB~OpenGLFontAtlas\fP () override=default"
.br
.ti -1c
.RI "virtual const \fBFontGlyph\fP & \fBGetCharacterTexture\fP (char c) const override"
.br
.ti -1c
.RI "virtual \fBRef\fP< \fBTexture2D\fP > \fBGetFontMap\fP () const override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBFontGlyph\fP > \fBm_atlas\fP"
.br
.ti -1c
.RI "\fBRef\fP< \fBTexture2D\fP > \fBm_fontMap\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::OpenGLFontAtlas::OpenGLFontAtlas (const std::string & fontPath)"

.SS "virtual Brigerad::OpenGLFontAtlas::~OpenGLFontAtlas ()\fC [override]\fP, \fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBFontGlyph\fP & Brigerad::OpenGLFontAtlas::GetCharacterTexture (char c) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::FontAtlas\fP\&.
.SS "virtual \fBRef\fP<\fBTexture2D\fP> Brigerad::OpenGLFontAtlas::GetFontMap () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::FontAtlas\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBFontGlyph\fP> Brigerad::OpenGLFontAtlas::m_atlas\fC [private]\fP"

.SS "\fBRef\fP<\fBTexture2D\fP> Brigerad::OpenGLFontAtlas::m_fontMap\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
