.TH "Brigerad::ImGuiInvisibleButtonComponent" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::ImGuiInvisibleButtonComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImGuiButtonComponents\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiInvisibleButtonComponent\fP ()=default"
.br
.ti -1c
.RI "\fBImGuiInvisibleButtonComponent\fP (const \fBImGuiInvisibleButtonComponent\fP &)=default"
.br
.ti -1c
.RI "\fBImGuiInvisibleButtonComponent\fP (const std::string &n, const ImVec2 &s=ImVec2(0, 0))"
.br
.ti -1c
.RI "void * \fBGetImGuiID\fP ()"
.br
.ti -1c
.RI "void * \fBGetImGuiID\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP = 'Button'"
.br
.ti -1c
.RI "\fBImGuiButtonState\fP \fBstate\fP = \fBImGuiButtonState::Inactive\fP"
.br
.ti -1c
.RI "ImGuiButtonFlags \fBflag\fP = ImGuiButtonFlags_MouseButtonLeft"
.br
.ti -1c
.RI "ImVec2 \fBsize\fP = ImVec2(0\&.1f, 0\&.1f)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::ImGuiInvisibleButtonComponent::ImGuiInvisibleButtonComponent ()\fC [default]\fP"

.SS "Brigerad::ImGuiInvisibleButtonComponent::ImGuiInvisibleButtonComponent (const \fBImGuiInvisibleButtonComponent\fP &)\fC [default]\fP"

.SS "Brigerad::ImGuiInvisibleButtonComponent::ImGuiInvisibleButtonComponent (const std::string & n, const ImVec2 & s = \fCImVec2(0, 0)\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void* Brigerad::ImGuiInvisibleButtonComponent::GetImGuiID ()\fC [inline]\fP"

.SS "void* Brigerad::ImGuiInvisibleButtonComponent::GetImGuiID () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Brigerad::ImGuiInvisibleButtonComponent::name = 'Button'"

.SS "\fBImGuiButtonState\fP Brigerad::ImGuiInvisibleButtonComponent::state = \fBImGuiButtonState::Inactive\fP"

.SS "ImGuiButtonFlags Brigerad::ImGuiInvisibleButtonComponent::flag = ImGuiButtonFlags_MouseButtonLeft"

.SS "ImVec2 Brigerad::ImGuiInvisibleButtonComponent::size = ImVec2(0\&.1f, 0\&.1f)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
