.TH "Brigerad::Memory" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Memory
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBMemAlloc\fP (size_t size)"
.br
.ti -1c
.RI "void \fBMemFree\fP (void *ptr)"
.br
.ti -1c
.RI "template<typename T > void \fBBR_DELETE\fP (T *p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * Brigerad::Memory::MemAlloc (size_t size)"

.SS "void Brigerad::Memory::MemFree (void * ptr)"

.SS "template<typename T > void Brigerad::Memory::BR_DELETE (T * p)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
