.TH "Brigerad::EventDispatcher" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::EventDispatcher
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Event\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventDispatcher\fP (\fBEvent\fP &event)"
.br
.ti -1c
.RI "template<typename T > bool \fBDispatch\fP (\fBEventFn\fP< T > func)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "template<typename T > using \fBEventFn\fP = std::function< bool(T &)>"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBEvent\fP & \fBm_event\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > using \fBBrigerad::EventDispatcher::EventFn\fP =  std::function<bool(T&)>\fC [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::EventDispatcher::EventDispatcher (\fBEvent\fP & event)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > bool Brigerad::EventDispatcher::Dispatch (\fBEventFn\fP< T > func)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEvent\fP& Brigerad::EventDispatcher::m_event\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
