.TH "Brigerad::OpenGLFramebuffer" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::OpenGLFramebuffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenGLFrameBuffer\&.h>\fP
.PP
Inherits \fBBrigerad::Framebuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenGLFramebuffer\fP (const \fBFramebufferSpecification\fP &spec)"
.br
.ti -1c
.RI "virtual \fB~OpenGLFramebuffer\fP ()"
.br
.ti -1c
.RI "void \fBInvalidate\fP ()"
.br
.ti -1c
.RI "virtual void \fBBind\fP () override"
.br
.ti -1c
.RI "virtual void \fBUnbind\fP () override"
.br
.ti -1c
.RI "virtual void \fBResize\fP (uint32_t width, uint32_t height) override"
.br
.ti -1c
.RI "virtual uint32_t \fBGetColorAttachmentRenderID\fP () const override"
.br
.ti -1c
.RI "virtual const \fBFramebufferSpecification\fP & \fBGetSpecification\fP () const override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBm_rendererID\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBm_colorAttachment\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBm_depthAttachment\fP = 0"
.br
.ti -1c
.RI "\fBFramebufferSpecification\fP \fBm_spec\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::OpenGLFramebuffer::OpenGLFramebuffer (const \fBFramebufferSpecification\fP & spec)"

.SS "Brigerad::OpenGLFramebuffer::~OpenGLFramebuffer ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Brigerad::OpenGLFramebuffer::Invalidate ()"

.SS "void Brigerad::OpenGLFramebuffer::Bind ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Framebuffer\fP\&.
.SS "void Brigerad::OpenGLFramebuffer::Unbind ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Framebuffer\fP\&.
.SS "void Brigerad::OpenGLFramebuffer::Resize (uint32_t width, uint32_t height)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Framebuffer\fP\&.
.SS "virtual uint32_t Brigerad::OpenGLFramebuffer::GetColorAttachmentRenderID () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Framebuffer\fP\&.
.SS "virtual const \fBFramebufferSpecification\fP& Brigerad::OpenGLFramebuffer::GetSpecification () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBBrigerad::Framebuffer\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t Brigerad::OpenGLFramebuffer::m_rendererID = 0\fC [private]\fP"

.SS "uint32_t Brigerad::OpenGLFramebuffer::m_colorAttachment = 0\fC [private]\fP"

.SS "uint32_t Brigerad::OpenGLFramebuffer::m_depthAttachment = 0\fC [private]\fP"

.SS "\fBFramebufferSpecification\fP Brigerad::OpenGLFramebuffer::m_spec\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
