.TH "Brigerad::AppUpdateEvent" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::AppUpdateEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ApplicationEvent\&.h>\fP
.PP
Inherits \fBBrigerad::Event\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppUpdateEvent\fP ()=default"
.br
.ti -1c
.RI "\fBEVENT_CLASS_TYPE\fP (\fBEventType::AppUpdate\fP)"
.br
.ti -1c
.RI "\fBEVENT_CLASS_CATEGORY\fP (\fBEventCategoryApplication\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::AppUpdateEvent::AppUpdateEvent ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "Brigerad::AppUpdateEvent::EVENT_CLASS_TYPE (\fBEventType::AppUpdate\fP)"

.SS "Brigerad::AppUpdateEvent::EVENT_CLASS_CATEGORY (\fBEventCategoryApplication\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
