.TH "Brigerad::Layer" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Layer \- \fBLayer\fP class, where most of the client's logic should occur\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Layer\&.h>\fP
.PP
Inherited by \fBBrigerad::ImGuiLayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayer\fP (const std::string &name='Layer')"
.br
.ti -1c
.RI "virtual \fB~Layer\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnAttach\fP ()"
.br
.RI "Called when the layer gets attached to the application\&. "
.ti -1c
.RI "virtual void \fBOnDetach\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUpdate\fP (\fBTimestep\fP timestep)"
.br
.ti -1c
.RI "virtual void \fBOnImGuiRender\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnEvent\fP (\fBEvent\fP &event)"
.br
.ti -1c
.RI "const std::string & \fBGetName\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_debugName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLayer\fP class, where most of the client's logic should occur\&. 

To use it in your client code, define a class that inherits from the layer and then override the functions you need\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::Layer::Layer (const std::string & name = \fC'Layer'\fP)"
The constructor of \fBLayer\fP\&. You shouldn't load your assets in here, but instead in the OnAttach method, where the layer is attached to the application\&.
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the layer\&. 
.RE
.PP

.SS "Brigerad::Layer::~Layer ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Brigerad::Layer::OnAttach ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Called when the layer gets attached to the application\&. 
.PP
Reimplemented in \fBBrigerad::ImGuiLayer\fP\&.
.SS "virtual void Brigerad::Layer::OnDetach ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBBrigerad::ImGuiLayer\fP\&.
.SS "virtual void Brigerad::Layer::OnUpdate (\fBTimestep\fP timestep)\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void Brigerad::Layer::OnImGuiRender ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBBrigerad::ImGuiLayer\fP\&.
.SS "virtual void Brigerad::Layer::OnEvent (\fBEvent\fP & event)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBBrigerad::ImGuiLayer\fP\&.
.SS "const std::string& Brigerad::Layer::GetName () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Brigerad::Layer::m_debugName\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
