.TH "Brigerad::MouseButtonReleasedEvent" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::MouseButtonReleasedEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MouseEvent\&.h>\fP
.PP
Inherits \fBBrigerad::MouseButtonEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMouseButtonReleasedEvent\fP (\fBMouseCode\fP button)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::MouseButtonReleasedEvent::MouseButtonReleasedEvent (\fBMouseCode\fP button)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string Brigerad::MouseButtonReleasedEvent::ToString () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBBrigerad::Event\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
