.TH "Brigerad::TextureRendererComponent" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::TextureRendererComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Components\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextureRendererComponent\fP ()=default"
.br
.ti -1c
.RI "\fBTextureRendererComponent\fP (const \fBTextureRendererComponent\fP &)=default"
.br
.ti -1c
.RI "\fBTextureRendererComponent\fP (const std::string &p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRef\fP< \fBTexture2D\fP > \fBtexture\fP = nullptr"
.br
.ti -1c
.RI "std::string \fBpath\fP = ''"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::TextureRendererComponent::TextureRendererComponent ()\fC [default]\fP"

.SS "Brigerad::TextureRendererComponent::TextureRendererComponent (const \fBTextureRendererComponent\fP &)\fC [default]\fP"

.SS "Brigerad::TextureRendererComponent::TextureRendererComponent (const std::string & p)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBRef\fP<\fBTexture2D\fP> Brigerad::TextureRendererComponent::texture = nullptr"

.SS "std::string Brigerad::TextureRendererComponent::path = ''"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
