.TH "Brigerad::RenderAPICapabilities" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::RenderAPICapabilities
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RendererAPI\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBvendor\fP = ''"
.br
.ti -1c
.RI "std::string \fBrenderer\fP = ''"
.br
.ti -1c
.RI "std::string \fBversion\fP = ''"
.br
.ti -1c
.RI "int \fBmaxSamples\fP = 0"
.br
.ti -1c
.RI "float \fBmaxAnisotropy\fP = 0\&.0f"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string Brigerad::RenderAPICapabilities::vendor = ''"

.SS "std::string Brigerad::RenderAPICapabilities::renderer = ''"

.SS "std::string Brigerad::RenderAPICapabilities::version = ''"

.SS "int Brigerad::RenderAPICapabilities::maxSamples = 0"

.SS "float Brigerad::RenderAPICapabilities::maxAnisotropy = 0\&.0f"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
