.TH "Brigerad::KeyTypedEvent" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::KeyTypedEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <KeyEvents\&.h>\fP
.PP
Inherits \fBBrigerad::KeyEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyTypedEvent\fP (\fBKeyCode\fP keycode)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::KeyTypedEvent::KeyTypedEvent (\fBKeyCode\fP keycode)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string Brigerad::KeyTypedEvent::ToString () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBBrigerad::Event\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
