.TH "Brigerad::Vertex" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBposition\fP"
.br
.ti -1c
.RI "glm::vec3 \fBnormal\fP"
.br
.ti -1c
.RI "glm::vec3 \fBtangent\fP"
.br
.ti -1c
.RI "glm::vec3 \fBbinormal\fP"
.br
.ti -1c
.RI "glm::vec2 \fBtexCoord\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 Brigerad::Vertex::position"

.SS "glm::vec3 Brigerad::Vertex::normal"

.SS "glm::vec3 Brigerad::Vertex::tangent"

.SS "glm::vec3 Brigerad::Vertex::binormal"

.SS "glm::vec2 Brigerad::Vertex::texCoord"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
