.TH "Brigerad::BrBoolVector" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::BrBoolVector
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBrBoolVector\fP ()"
.br
.ti -1c
.RI "void \fBResize\fP (int sz)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBGetBit\fP (int n) const"
.br
.ti -1c
.RI "void \fBSetBit\fP (int n, bool v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< int > \fBStorage\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::BrBoolVector::BrBoolVector ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Brigerad::BrBoolVector::Resize (int sz)\fC [inline]\fP"

.SS "void Brigerad::BrBoolVector::Clear ()\fC [inline]\fP"

.SS "bool Brigerad::BrBoolVector::GetBit (int n) const\fC [inline]\fP"

.SS "void Brigerad::BrBoolVector::SetBit (int n, bool v)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<int> Brigerad::BrBoolVector::Storage"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
