.TH "Brigerad::QuadVertex" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::QuadVertex \- Data structure that contains all the information needed by a quad\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBposition\fP"
.br
.ti -1c
.RI "glm::vec4 \fBcolor\fP"
.br
.ti -1c
.RI "glm::vec2 \fBtexCoord\fP"
.br
.ti -1c
.RI "glm::vec2 \fBtilingFactor\fP"
.br
.ti -1c
.RI "float \fBtexIndex\fP"
.br
.ti -1c
.RI "float \fBisText\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure that contains all the information needed by a quad\&. 
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 Brigerad::QuadVertex::position"

.SS "glm::vec4 Brigerad::QuadVertex::color"

.SS "glm::vec2 Brigerad::QuadVertex::texCoord"

.SS "glm::vec2 Brigerad::QuadVertex::tilingFactor"

.SS "float Brigerad::QuadVertex::texIndex"

.SS "float Brigerad::QuadVertex::isText"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
