.TH "Brigerad::LightComponent::Light" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::LightComponent::Light
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Components\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBDirection\fP = glm::vec3()"
.br
.ti -1c
.RI "glm::vec3 \fBRadiance\fP = glm::vec3()"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 Brigerad::LightComponent::Light::Direction = glm::vec3()"

.SS "glm::vec3 Brigerad::LightComponent::Light::Radiance = glm::vec3()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
