.TH "Brigerad::NativeScriptComponent" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::NativeScriptComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Components\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBBind\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBScriptableEntity\fP * \fBinstance\fP = nullptr"
.br
.ti -1c
.RI "\fBScriptableEntity\fP *(* \fBinstantiateScript\fP )() = nullptr"
.br
.ti -1c
.RI "void(* \fBdestroyScript\fP )(\fBNativeScriptComponent\fP *) = nullptr"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void Brigerad::NativeScriptComponent::Bind ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBScriptableEntity\fP* Brigerad::NativeScriptComponent::instance = nullptr"

.SS "\fBScriptableEntity\fP*(* Brigerad::NativeScriptComponent::instantiateScript) () = nullptr"

.SS "void(* Brigerad::NativeScriptComponent::destroyScript) (\fBNativeScriptComponent\fP *) = nullptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
