.TH "Brigerad::Renderer::SceneData" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Renderer::SceneData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::mat4 \fBViewProjectionMatrix\fP"
.br
.ti -1c
.RI "long long \fBFrameCount\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::mat4 Brigerad::Renderer::SceneData::ViewProjectionMatrix"

.SS "long long Brigerad::Renderer::SceneData::FrameCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
