.TH "Brigerad::ProfileResult" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::ProfileResult
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Instrumentor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "long long \fBStart\fP"
.br
.ti -1c
.RI "long long \fBEnd\fP"
.br
.ti -1c
.RI "uint32_t \fBThreadID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string Brigerad::ProfileResult::Name"

.SS "long long Brigerad::ProfileResult::Start"

.SS "long long Brigerad::ProfileResult::End"

.SS "uint32_t Brigerad::ProfileResult::ThreadID"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
