.TH "Brigerad::Vec2" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Vec2 \- 2D vector (Often used to store positions, size, etc\&.)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec2\fP ()"
.br
.ti -1c
.RI "\fBVec2\fP (float _x, float _y)"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator+\fP (const \fBVec2\fP &other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator\-\fP (const \fBVec2\fP &other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator*\fP (const \fBVec2\fP &other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator/\fP (const \fBVec2\fP &other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator+\fP (float other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator\-\fP (float other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator*\fP (float other) const"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator/\fP (float other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
2D vector (Often used to store positions, size, etc\&.) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::Vec2::Vec2 ()\fC [inline]\fP"

.SS "Brigerad::Vec2::Vec2 (float _x, float _y)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBVec2\fP Brigerad::Vec2::operator+ (const \fBVec2\fP & other) const\fC [inline]\fP"

.SS "\fBVec2\fP Brigerad::Vec2::operator\- (const \fBVec2\fP & other) const\fC [inline]\fP"

.SS "\fBVec2\fP Brigerad::Vec2::operator* (const \fBVec2\fP & other) const\fC [inline]\fP"

.SS "\fBVec2\fP Brigerad::Vec2::operator/ (const \fBVec2\fP & other) const\fC [inline]\fP"

.SS "\fBVec2\fP Brigerad::Vec2::operator+ (float other) const\fC [inline]\fP"

.SS "\fBVec2\fP Brigerad::Vec2::operator\- (float other) const\fC [inline]\fP"

.SS "\fBVec2\fP Brigerad::Vec2::operator* (float other) const\fC [inline]\fP"

.SS "\fBVec2\fP Brigerad::Vec2::operator/ (float other) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float Brigerad::Vec2::x"

.SS "float Brigerad::Vec2::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
