.TH "Brigerad::Event" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Event\&.h>\fP
.PP
Inherited by \fBBrigerad::AppRenderEvent\fP, \fBBrigerad::AppTickEvent\fP, \fBBrigerad::AppUpdateEvent\fP, \fBBrigerad::ImGuiButtonEvent\fP, \fBBrigerad::KeyEvent\fP, \fBBrigerad::MouseButtonEvent\fP, \fBBrigerad::MouseMovedEvent\fP, \fBBrigerad::MouseScrolledEvent\fP, \fBBrigerad::WindowCloseEvent\fP, and \fBBrigerad::WindowResizeEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Event\fP ()=default"
.br
.ti -1c
.RI "virtual \fBEventType\fP \fBGetEventType\fP () const =0"
.br
.ti -1c
.RI "virtual const char * \fBGetName\fP () const =0"
.br
.ti -1c
.RI "virtual int \fBGetCategoryFlags\fP () const =0"
.br
.ti -1c
.RI "virtual std::string \fBToString\fP () const"
.br
.ti -1c
.RI "bool \fBIsInCategory\fP (\fBEventCategory\fP category)"
.br
.ti -1c
.RI "bool \fBHandled\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_handled\fP = false"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEventDispatcher\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Brigerad::Event::~Event ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBEventType\fP Brigerad::Event::GetEventType () const\fC [pure virtual]\fP"

.SS "virtual const char* Brigerad::Event::GetName () const\fC [pure virtual]\fP"

.SS "virtual int Brigerad::Event::GetCategoryFlags () const\fC [pure virtual]\fP"

.SS "virtual std::string Brigerad::Event::ToString () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBBrigerad::MouseButtonReleasedEvent\fP, \fBBrigerad::MouseButtonPressedEvent\fP, \fBBrigerad::MouseScrolledEvent\fP, \fBBrigerad::MouseMovedEvent\fP, \fBBrigerad::KeyTypedEvent\fP, \fBBrigerad::KeyReleasedEvent\fP, \fBBrigerad::KeyPressedEvent\fP, \fBBrigerad::ImGuiButtonReleasedEvent\fP, \fBBrigerad::ImGuiButtonPressedEvent\fP, and \fBBrigerad::WindowResizeEvent\fP\&.
.SS "bool Brigerad::Event::IsInCategory (\fBEventCategory\fP category)\fC [inline]\fP"

.SS "bool Brigerad::Event::Handled ()\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBEventDispatcher\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool Brigerad::Event::m_handled = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
