.TH "Brigerad::Index" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Index
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBv1\fP"
.br
.ti -1c
.RI "uint32_t \fBv2\fP"
.br
.ti -1c
.RI "uint32_t \fBv3\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint32_t Brigerad::Index::v1"

.SS "uint32_t Brigerad::Index::v2"

.SS "uint32_t Brigerad::Index::v3"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
