.TH "Brigerad::Camera" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Camera
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Camera\&.h>\fP
.PP
Inherited by \fBBrigerad::SceneCamera\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP ()=default"
.br
.ti -1c
.RI "\fBCamera\fP (const glm::mat4 &projection)"
.br
.ti -1c
.RI "virtual \fB~Camera\fP ()=default"
.br
.ti -1c
.RI "const glm::mat4 & \fBGetProjection\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "glm::mat4 \fBm_projection\fP = glm::mat4(1\&.0f)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::Camera::Camera ()\fC [default]\fP"

.SS "Brigerad::Camera::Camera (const glm::mat4 & projection)\fC [inline]\fP"

.SS "virtual Brigerad::Camera::~Camera ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const glm::mat4& Brigerad::Camera::GetProjection () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::mat4 Brigerad::Camera::m_projection = glm::mat4(1\&.0f)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
