.TH "Brigerad::ImGuiArrowButtonComponent" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::ImGuiArrowButtonComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImGuiButtonComponents\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiArrowButtonComponent\fP ()=default"
.br
.ti -1c
.RI "\fBImGuiArrowButtonComponent\fP (const \fBImGuiArrowButtonComponent\fP &)=default"
.br
.ti -1c
.RI "\fBImGuiArrowButtonComponent\fP (const std::string &n, ImGuiDir dir=ImGuiDir_Left)"
.br
.ti -1c
.RI "void * \fBGetImGuiID\fP ()"
.br
.ti -1c
.RI "void * \fBGetImGuiID\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP = 'Button'"
.br
.ti -1c
.RI "\fBImGuiButtonState\fP \fBstate\fP = \fBImGuiButtonState::Inactive\fP"
.br
.ti -1c
.RI "ImGuiDir \fBdirection\fP = ImGuiDir_Left"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::ImGuiArrowButtonComponent::ImGuiArrowButtonComponent ()\fC [default]\fP"

.SS "Brigerad::ImGuiArrowButtonComponent::ImGuiArrowButtonComponent (const \fBImGuiArrowButtonComponent\fP &)\fC [default]\fP"

.SS "Brigerad::ImGuiArrowButtonComponent::ImGuiArrowButtonComponent (const std::string & n, ImGuiDir dir = \fCImGuiDir_Left\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void* Brigerad::ImGuiArrowButtonComponent::GetImGuiID ()\fC [inline]\fP"

.SS "void* Brigerad::ImGuiArrowButtonComponent::GetImGuiID () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Brigerad::ImGuiArrowButtonComponent::name = 'Button'"

.SS "\fBImGuiButtonState\fP Brigerad::ImGuiArrowButtonComponent::state = \fBImGuiButtonState::Inactive\fP"

.SS "ImGuiDir Brigerad::ImGuiArrowButtonComponent::direction = ImGuiDir_Left"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
