.TH "Brigerad::LuaScriptEntity" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::LuaScriptEntity
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScriptEngine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLuaScriptEntity\fP (const std::string &path, const std::string &name)"
.br
.ti -1c
.RI "virtual \fB~LuaScriptEntity\fP ()=default"
.br
.ti -1c
.RI "const std::string & \fBGetPath\fP () const"
.br
.ti -1c
.RI "const std::string & \fBGetName\fP () const"
.br
.ti -1c
.RI "void \fBReload\fP ()"
.br
.ti -1c
.RI "template<typename T > T & \fBGetComponentRef\fP ()"
.br
.ti -1c
.RI "template<typename T > const T & \fBGetComponent\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnCreate\fP ()"
.br
.ti -1c
.RI "void \fBOnUpdate\fP (\fBTimestep\fP ts)"
.br
.ti -1c
.RI "void \fBOnRender\fP ()"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBEntity\fP \fBm_entity\fP"
.br
.ti -1c
.RI "std::string \fBm_path\fP = ''"
.br
.ti -1c
.RI "std::string \fBm_name\fP = ''"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Brigerad::LuaScriptEntity::LuaScriptEntity (const std::string & path, const std::string & name)"

.SS "virtual Brigerad::LuaScriptEntity::~LuaScriptEntity ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const std::string& Brigerad::LuaScriptEntity::GetPath () const\fC [inline]\fP"

.SS "const std::string& Brigerad::LuaScriptEntity::GetName () const\fC [inline]\fP"

.SS "void Brigerad::LuaScriptEntity::Reload ()"

.SS "template<typename T > T& Brigerad::LuaScriptEntity::GetComponentRef ()\fC [inline]\fP"

.SS "template<typename T > const T& Brigerad::LuaScriptEntity::GetComponent () const\fC [inline]\fP"

.SS "void Brigerad::LuaScriptEntity::OnCreate ()\fC [protected]\fP"

.SS "void Brigerad::LuaScriptEntity::OnUpdate (\fBTimestep\fP ts)\fC [protected]\fP"

.SS "void Brigerad::LuaScriptEntity::OnRender ()\fC [protected]\fP"

.SS "void Brigerad::LuaScriptEntity::OnDestroy ()\fC [protected]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBScene\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEntity\fP Brigerad::LuaScriptEntity::m_entity\fC [private]\fP"

.SS "std::string Brigerad::LuaScriptEntity::m_path = ''\fC [private]\fP"

.SS "std::string Brigerad::LuaScriptEntity::m_name = ''\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
