.TH "Brigerad::RenderCommand" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::RenderCommand
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RenderCommand\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetClearColor\fP (const glm::vec4 &color)"
.br
.ti -1c
.RI "static void \fBSetViewport\fP (uint32_t x, uint32_t y, uint32_t width, uint32_t height)"
.br
.ti -1c
.RI "static void \fBClear\fP ()"
.br
.ti -1c
.RI "static void \fBDrawIndexed\fP (const \fBRef\fP< \fBVertexArray\fP > &vertexArray, uint32_t count=0)"
.br
.ti -1c
.RI "static void \fBInit\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBRendererAPI\fP * \fBs_rendererAPI\fP = new \fBOpenGLRendererAPI\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void Brigerad::RenderCommand::SetClearColor (const glm::vec4 & color)\fC [inline]\fP, \fC [static]\fP"

.SS "static void Brigerad::RenderCommand::SetViewport (uint32_t x, uint32_t y, uint32_t width, uint32_t height)\fC [inline]\fP, \fC [static]\fP"

.SS "static void Brigerad::RenderCommand::Clear ()\fC [inline]\fP, \fC [static]\fP"

.SS "static void Brigerad::RenderCommand::DrawIndexed (const \fBRef\fP< \fBVertexArray\fP > & vertexArray, uint32_t count = \fC0\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static void Brigerad::RenderCommand::Init ()\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBRendererAPI\fP * Brigerad::RenderCommand::s_rendererAPI = new \fBOpenGLRendererAPI\fP\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
