.TH "Brigerad::Renderer2D::Statistics" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::Renderer2D::Statistics
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Renderer2D\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBGetTotalVertexCount\fP ()"
.br
.ti -1c
.RI "uint32_t \fBGetTotalIndexCount\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBdrawCalls\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBquadCount\fP = 0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "uint32_t Brigerad::Renderer2D::Statistics::GetTotalVertexCount ()\fC [inline]\fP"

.SS "uint32_t Brigerad::Renderer2D::Statistics::GetTotalIndexCount ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint32_t Brigerad::Renderer2D::Statistics::drawCalls = 0"

.SS "uint32_t Brigerad::Renderer2D::Statistics::quadCount = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
