.TH "Brigerad::UniformBufferBase" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Brigerad::UniformBufferBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Shader\&.h>\fP
.PP
Inherited by \fBBrigerad::UniformBufferDeclaration< N, U >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const \fBbyte\fP * \fBGetBuffer\fP () const =0"
.br
.ti -1c
.RI "virtual const \fBUniformDecl\fP * \fBGetUniforms\fP () const =0"
.br
.ti -1c
.RI "virtual unsigned int \fBGetUniformCount\fP () const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual const \fBbyte\fP* Brigerad::UniformBufferBase::GetBuffer () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::UniformBufferDeclaration< N, U >\fP\&.
.SS "virtual const \fBUniformDecl\fP* Brigerad::UniformBufferBase::GetUniforms () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::UniformBufferDeclaration< N, U >\fP\&.
.SS "virtual unsigned int Brigerad::UniformBufferBase::GetUniformCount () const\fC [pure virtual]\fP"

.PP
Implemented in \fBBrigerad::UniformBufferDeclaration< N, U >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
