.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Buffer.h" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Buffer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Brigerad/Core/Core\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBrigerad::BufferElements\fP"
.br
.ti -1c
.RI "class \fBBrigerad::BufferLayout\fP"
.br
.ti -1c
.RI "class \fBBrigerad::VertexBuffer\fP"
.br
.ti -1c
.RI "class \fBBrigerad::IndexBuffer\fP"
.br
.RI "Wrapper around an index buffer inside of the GPU's memory\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBBrigerad::ShaderDataType\fP { \fBBrigerad::None\fP = 0, \fBBrigerad::Float\fP, \fBBrigerad::Float2\fP, \fBBrigerad::Float3\fP, \fBBrigerad::Float4\fP, \fBBrigerad::Mat3\fP, \fBBrigerad::Mat4\fP, \fBBrigerad::Int\fP, \fBBrigerad::Int2\fP, \fBBrigerad::Int3\fP, \fBBrigerad::Int4\fP, \fBBrigerad::Bool\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
