.TH "F:/dev/Brigerad/Brigerad/src Directory Reference" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBrigerad\fP"
.br
.ti -1c
.RI "directory \fBPlatform\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBrigerad\&.h\fP"
.br
.ti -1c
.RI "file \fBbrpch\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbrpch\&.h\fP"
.br
.in -1c
