.TH "F:/dev/Brigerad/Brigerad/src/Platform Directory Reference" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Platform Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBLinux\fP"
.br
.ti -1c
.RI "directory \fBOpenGL\fP"
.br
.ti -1c
.RI "directory \fBWindows\fP"
.br
.in -1c
