.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/FontAtlas.cpp" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/FontAtlas.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'FontAtlas\&.h'\fP
.br
\fC#include 'Renderer\&.h'\fP
.br
\fC#include 'Platform/OpenGL/OpenGLFontAtlas\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
