.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Scene/ImGuiButtonComponents.h" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Scene/ImGuiButtonComponents.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Brigerad/Scene/Entity\&.h'\fP
.br
\fC#include 'imgui\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBrigerad::ImGuiButtonListenerComponent< T >\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::ImGuiButtonComponent\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::ImGuiSmallButtonComponent\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::ImGuiInvisibleButtonComponent\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::ImGuiArrowButtonComponent\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::ImGuiCheckboxComponent\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBBrigerad::ImGuiButtonState\fP { \fBBrigerad::Inactive\fP = 0, \fBBrigerad::Pressed\fP = 1, \fBBrigerad::Held\fP = 2, \fBBrigerad::Released\fP = 3 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
