.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/ImGui/ImGuiBuild.cpp" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/ImGui/ImGuiBuild.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'examples/imgui_impl_glfw\&.cpp'\fP
.br
\fC#include 'examples/imgui_impl_opengl3\&.cpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_LOADER_GLAD\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IMGUI_IMPL_OPENGL_LOADER_GLAD"

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
