.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/ImGui/ImGuiLayer.cpp" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/ImGui/ImGuiLayer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'ImGuiLayer\&.h'\fP
.br
\fC#include 'imgui\&.h'\fP
.br
\fC#include 'examples/imgui_impl_glfw\&.h'\fP
.br
\fC#include 'examples/imgui_impl_opengl3\&.h'\fP
.br
\fC#include 'Brigerad/Core/Application\&.h'\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include <glad/glad\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
