.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Material.cpp" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Material.cpp \- Source for the Material system\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'Material\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Shader\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Source for the Material system\&. 


.PP
\fBAuthor\fP
.RS 4
Samuel Martel 
.RE
.PP
\fBDate\fP
.RS 4
06/02/2021 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
