.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Material.h" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Material.h \- Header for the Material system\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Brigerad/Core/Core\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Shader\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Texture\&.h'\fP
.br
\fC#include <unordered_set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrigerad::Material\fP"
.br
.RI "Platform-agnostic \fBMaterial\fP class\&. "
.ti -1c
.RI "class \fBBrigerad::MaterialInstance\fP"
.br
.RI "An instance of a \fBMaterial\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for the Material system\&. 


.PP
\fBAuthor\fP
.RS 4
Samuel Martel 
.RE
.PP
\fBDate\fP
.RS 4
06/02/2021 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
