.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Mesh.h" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Mesh.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'Brigerad/Core/Core\&.h'\fP
.br
\fC#include 'Brigerad/Core/Timestep\&.h'\fP
.br
\fC#include 'Shader\&.h'\fP
.br
\fC#include 'Texture\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Material\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBrigerad::Vertex\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::AnimatedVertex\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::Index\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::BoneInfo\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::VertexBoneData\fP"
.br
.ti -1c
.RI "class \fBBrigerad::Submesh\fP"
.br
.ti -1c
.RI "class \fBBrigerad::Mesh\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
