.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Core/MouseButtonCodes.h" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Core/MouseButtonCodes.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_0\fP   ::Brigerad::Mouse::Button0"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_1\fP   ::Brigerad::Mouse::Button1"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_2\fP   ::Brigerad::Mouse::Button2"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_3\fP   ::Brigerad::Mouse::Button3"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_4\fP   ::Brigerad::Mouse::Button4"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_5\fP   ::Brigerad::Mouse::Button5"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_6\fP   ::Brigerad::Mouse::Button6"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_7\fP   ::Brigerad::Mouse::Button7"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_LAST\fP   ::Brigerad::Mouse::ButtonLast"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_LEFT\fP   ::Brigerad::Mouse::ButtonLeft"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_RIGHT\fP   ::Brigerad::Mouse::ButtonRight"
.br
.ti -1c
.RI "#define \fBBR_MOUSE_BUTTON_MIDDLE\fP   ::Brigerad::Mouse::ButtonMiddle"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBBrigerad::MouseCode\fP \fBBrigerad::Mouse\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBBrigerad::MouseCode\fP : uint16_t { \fBBrigerad::Button0\fP = 0, \fBBrigerad::Button1\fP = 1, \fBBrigerad::Button2\fP = 2, \fBBrigerad::Button3\fP = 3, \fBBrigerad::Button4\fP = 4, \fBBrigerad::Button5\fP = 5, \fBBrigerad::Button6\fP = 6, \fBBrigerad::Button7\fP = 7, \fBBrigerad::ButtonLast\fP = Button7, \fBBrigerad::ButtonLeft\fP = Button0, \fBBrigerad::ButtonRight\fP = Button1, \fBBrigerad::ButtonMiddle\fP = Button2 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBBrigerad::operator<<\fP (std::ostream &os, MouseCode mouseCode)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BR_MOUSE_BUTTON_0   ::Brigerad::Mouse::Button0"

.SS "#define BR_MOUSE_BUTTON_1   ::Brigerad::Mouse::Button1"

.SS "#define BR_MOUSE_BUTTON_2   ::Brigerad::Mouse::Button2"

.SS "#define BR_MOUSE_BUTTON_3   ::Brigerad::Mouse::Button3"

.SS "#define BR_MOUSE_BUTTON_4   ::Brigerad::Mouse::Button4"

.SS "#define BR_MOUSE_BUTTON_5   ::Brigerad::Mouse::Button5"

.SS "#define BR_MOUSE_BUTTON_6   ::Brigerad::Mouse::Button6"

.SS "#define BR_MOUSE_BUTTON_7   ::Brigerad::Mouse::Button7"

.SS "#define BR_MOUSE_BUTTON_LAST   ::Brigerad::Mouse::ButtonLast"

.SS "#define BR_MOUSE_BUTTON_LEFT   ::Brigerad::Mouse::ButtonLeft"

.SS "#define BR_MOUSE_BUTTON_RIGHT   ::Brigerad::Mouse::ButtonRight"

.SS "#define BR_MOUSE_BUTTON_MIDDLE   ::Brigerad::Mouse::ButtonMiddle"

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
