.TH "F:/dev/Brigerad/Brigerad/src/Platform/OpenGL/OpenGLShaderUniform.h" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Platform/OpenGL/OpenGLShaderUniform.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Brigerad/Renderer/ShaderUniform\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrigerad::OpenGLShaderResourceDeclaration\fP"
.br
.ti -1c
.RI "class \fBBrigerad::OpenGLShaderUniformDeclaration\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::GLShaderUniformField\fP"
.br
.ti -1c
.RI "class \fBBrigerad::OpenGLShaderUniformBufferDeclaration\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
