.TH "F:/dev/Brigerad/Brigerad/src/Platform/OpenGL/OpenGLFontAtlas.cpp" 3 "Sun Jan 10 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Platform/OpenGL/OpenGLFontAtlas.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'OpenGLFontAtlas\&.h'\fP
.br
\fC#include 'imstb_truetype\&.h'\fP
.br
\fC#include 'stb_image_write\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <array>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTB_TRUETYPE_IMPLEMENTATION\fP"
.br
.ti -1c
.RI "#define \fBSTB_IMAGE_WRITE_IMPLEMENTATION\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STB_TRUETYPE_IMPLEMENTATION"

.SS "#define STB_IMAGE_WRITE_IMPLEMENTATION"

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
