.TH "F:/dev/Brigerad/Brigerad/src/Platform/OpenGL/OpenGLMesh.cpp" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Platform/OpenGL/OpenGLMesh.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'OpenGLMesh\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Renderer\&.h'\fP
.br
\fC#include 'glm/ext/matrix_transform\&.hpp'\fP
.br
\fC#include 'glm/gtc/quaternion\&.hpp'\fP
.br
\fC#include 'glm/gtx/quaternion\&.hpp'\fP
.br
\fC#include 'assimp/scene\&.h'\fP
.br
\fC#include 'assimp/postprocess\&.h'\fP
.br
\fC#include 'assimp/Importer\&.hpp'\fP
.br
\fC#include 'assimp/DefaultLogger\&.hpp'\fP
.br
\fC#include 'assimp/LogStream\&.hpp'\fP
.br
\fC#include 'imgui\&.h'\fP
.br
\fC#include 'glad/glad\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBrigerad::LogStream\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLM_ENABLE_EXPERIMENTAL\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLM_ENABLE_EXPERIMENTAL"

.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
