.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/OrthographicCameraController.cpp" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/OrthographicCameraController.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'OrthographicCameraController\&.h'\fP
.br
\fC#include 'Brigerad/Core/Input\&.h'\fP
.br
\fC#include 'Brigerad/Core/KeyCodes\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr float \fBBrigerad::MAX_POS_SPEED\fP = 10\&.0f"
.br
.ti -1c
.RI "constexpr float \fBBrigerad::MAX_NEG_SPEED\fP = \-10\&.0f"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
