.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Renderer2D.cpp" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Renderer2D.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'Renderer2D\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/VertexArray\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Shader\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/RenderCommand\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/FontAtlas\&.h'\fP
.br
\fC#include 'glm/gtc/matrix_transform\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBrigerad::QuadVertex\fP"
.br
.RI "Data structure that contains all the information needed by a quad\&. "
.ti -1c
.RI "struct \fBBrigerad::Renderer2DData\fP"
.br
.RI "Runtime data structure that contains all the things needed by the renderer at runtime\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
