.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Renderer2D.h" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/Renderer2D.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Brigerad/Renderer/OrthographicCamera\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Camera\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Texture\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/SubTexture2D\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrigerad::Renderer2D\fP"
.br
.ti -1c
.RI "struct \fBBrigerad::Renderer2D::Statistics\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
