.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Scene/Scene.cpp" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Scene/Scene.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'brpch\&.h'\fP
.br
\fC#include 'Scene\&.h'\fP
.br
\fC#include 'Components\&.h'\fP
.br
\fC#include 'Entity\&.h'\fP
.br
\fC#include 'Brigerad/Renderer/Renderer2D\&.h'\fP
.br
\fC#include 'Brigerad/Core/Application\&.h'\fP
.br
\fC#include 'imgui\&.h'\fP
.br
\fC#include 'imgui_internal\&.h'\fP
.br
\fC#include 'glm/glm\&.hpp'\fP
.br
\fC#include 'examples/imgui_impl_glfw\&.h'\fP
.br
\fC#include 'examples/imgui_impl_opengl3\&.h'\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include <glad/glad\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBBrigerad::DrawImGuiButton\fP (Entity &entity, const std::function< bool(T &)> &func)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
