.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Scene/ScriptableEntity.h" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Scene/ScriptableEntity.h \- Copyright (C) 2020 Samuel Martel\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Entity\&.h'\fP
.br
\fC#include 'Brigerad/Core/Timestep\&.h'\fP
.br
\fC#include 'Brigerad/Script/ScriptEngine\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrigerad::ScriptableEntity\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (C) 2020 Samuel Martel\&. 


.PP
\fBAuthor\fP
.RS 4
Samuel Martel \fChttps://github.com/smartel99\fP 
.RE
.PP
\fBDate\fP
.RS 4
10/10/2020 2:31:47 PM
.RE
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program\&. If not, see https://www.gnu.org/licenses/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
