.TH "F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/ShaderUniform.h" 3 "Sun Feb 7 2021" "Version 0.2" "Brigerad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/dev/Brigerad/Brigerad/src/Brigerad/Renderer/ShaderUniform.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Brigerad/Core/Core\&.h'\fP
.br
\fC#include 'Brigerad/Core/Log\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrigerad::ShaderUniformDeclaration\fP"
.br
.ti -1c
.RI "class \fBBrigerad::ShaderUniformBufferDeclaration\fP"
.br
.ti -1c
.RI "class \fBBrigerad::ShaderStruct\fP"
.br
.ti -1c
.RI "class \fBBrigerad::ShaderResourceDeclaration\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBrigerad\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBBrigerad::ShaderUniformDeclarationList\fP = std::vector< ShaderUniformDeclaration * >"
.br
.ti -1c
.RI "using \fBBrigerad::ShaderUniformBufferList\fP = std::vector< ShaderUniformBufferDeclaration * >"
.br
.ti -1c
.RI "using \fBBrigerad::ShaderStructList\fP = std::vector< ShaderStruct * >"
.br
.ti -1c
.RI "using \fBBrigerad::ShaderResourceList\fP = std::vector< ShaderResourceDeclaration * >"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBBrigerad::ShaderDomain\fP { \fBBrigerad::None\fP = 0, \fBBrigerad::Vertex\fP = 0, \fBBrigerad::Pixel\fP = 1 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Brigerad from the source code\&.
